export function generateAdsTxtContent(): string {
  const adsenseClientId = process.env.NEXT_PUBLIC_ADSENSE_CLIENT_ID;
  
  if (!adsenseClientId) {
    return '';
  }
  
  // Extract publisher ID from client ID (remove 'ca-pub-' prefix)
  const publisherId = adsenseClientId.replace('ca-pub-', '');
  
  return `# ads.txt file for Google AdSense
# This file is auto-generated by the Landing Page Builder
google.com, pub-${publisherId}, DIRECT, f08c47fec0942fa0`;
}

export function shouldGenerateAdsTxt(): boolean {
  return !!process.env.NEXT_PUBLIC_ADSENSE_CLIENT_ID;
}